// Deferred EN 16931 rules — typed no-op stubs.
//
// These rule IDs belong to the KoSIT 2.5.0 rule set (see
// __tests__/fixtures/kosit-corpus/manifest.json) but their predicate logic is not
// yet implemented. They ship as no-op stubs (run: () => null) so the coverage
// assertion (rules.coverage.test.ts) holds and so that giving each one a real body
// later is a localized change with no engine wiring churn.
//
// When you implement a rule: remove its entry here and add the real Rule object to
// the appropriate en16931-*.ts / xrechnung-de.ts file with PASS+FAIL unit tests.

import type { Rule } from "./engine.js";

const stub = (id: string, category: Rule["category"]): Rule => ({
  id,
  category,
  severity: "error",
  citation: "EN 16931:2017 (rule predicate not yet implemented)",
  summary: `Deferred stub for ${id} — no validation performed yet.`,
  run: () => null,
});

export const deferredRules: readonly Rule[] = [
  stub("BR-33", "BR"),
  stub("BR-38", "BR"),
  stub("BR-41", "BR"),
  stub("BR-42", "BR"),
  stub("BR-43", "BR"),
  stub("BR-44", "BR"),
  stub("BR-49", "BR"),
  stub("BR-51", "BR"),
  stub("BR-53", "BR"),
  stub("BR-54", "BR"),
  stub("BR-55", "BR"),
  stub("BR-AE-02", "BR-AE"),
  stub("BR-AE-03", "BR-AE"),
  stub("BR-AE-04", "BR-AE"),
  stub("BR-AE-05", "BR-AE"),
  stub("BR-AE-06", "BR-AE"),
  stub("BR-AE-07", "BR-AE"),
  stub("BR-AE-08", "BR-AE"),
  stub("BR-AF-01", "BR"),
  stub("BR-AF-02", "BR"),
  stub("BR-AF-03", "BR"),
  stub("BR-AF-04", "BR"),
  stub("BR-AF-05", "BR"),
  stub("BR-AF-06", "BR"),
  stub("BR-AF-07", "BR"),
  stub("BR-AF-08", "BR"),
  stub("BR-AF-09", "BR"),
  stub("BR-AF-10", "BR"),
  stub("BR-AG-01", "BR"),
  stub("BR-AG-02", "BR"),
  stub("BR-AG-03", "BR"),
  stub("BR-AG-04", "BR"),
  stub("BR-AG-05", "BR"),
  stub("BR-AG-06", "BR"),
  stub("BR-AG-07", "BR"),
  stub("BR-AG-08", "BR"),
  stub("BR-AG-09", "BR"),
  stub("BR-AG-10", "BR"),
  stub("BR-B-01", "BR"),
  stub("BR-B-02", "BR"),
  stub("BR-CL-05", "BR-CL"),
  stub("BR-CL-11", "BR-CL"),
  stub("BR-CL-18", "BR-CL"),
  stub("BR-CL-22", "BR-CL"),
  stub("BR-CL-26", "BR-CL"),
  stub("BR-CO-03", "BR-CO"),
  stub("BR-CO-05", "BR-CO"),
  stub("BR-CO-06", "BR-CO"),
  stub("BR-CO-07", "BR-CO"),
  stub("BR-CO-08", "BR-CO"),
  stub("BR-DEC-01", "BR-DEC"),
  stub("BR-DEC-02", "BR-DEC"),
  stub("BR-DEC-05", "BR-DEC"),
  stub("BR-DEC-06", "BR-DEC"),
  stub("BR-DEC-09", "BR-DEC"),
  stub("BR-DEC-10", "BR-DEC"),
  stub("BR-DEC-11", "BR-DEC"),
  stub("BR-DEC-12", "BR-DEC"),
  stub("BR-DEC-13", "BR-DEC"),
  stub("BR-DEC-14", "BR-DEC"),
  stub("BR-DEC-15", "BR-DEC"),
  stub("BR-DEC-16", "BR-DEC"),
  stub("BR-DEC-17", "BR-DEC"),
  stub("BR-DEC-18", "BR-DEC"),
  stub("BR-DEC-19", "BR-DEC"),
  stub("BR-DEC-20", "BR-DEC"),
  stub("BR-DEC-23", "BR-DEC"),
  stub("BR-DEC-24", "BR-DEC"),
  stub("BR-DEC-25", "BR-DEC"),
  stub("BR-DEC-27", "BR-DEC"),
  stub("BR-DEC-28", "BR-DEC"),
  stub("BR-E-02", "BR-E"),
  stub("BR-E-03", "BR-E"),
  stub("BR-E-04", "BR-E"),
  stub("BR-E-05", "BR-E"),
  stub("BR-E-06", "BR-E"),
  stub("BR-E-07", "BR-E"),
  stub("BR-E-08", "BR-E"),
  stub("BR-E-09", "BR-E"),
  stub("BR-G-01", "BR-G"),
  stub("BR-G-02", "BR-G"),
  stub("BR-G-03", "BR-G"),
  stub("BR-G-04", "BR-G"),
  stub("BR-G-05", "BR-G"),
  stub("BR-G-06", "BR-G"),
  stub("BR-G-07", "BR-G"),
  stub("BR-G-08", "BR-G"),
  stub("BR-G-09", "BR-G"),
  stub("BR-G-10", "BR-G"),
  stub("BR-IC-02", "BR-IC"),
  stub("BR-IC-03", "BR-IC"),
  stub("BR-IC-04", "BR-IC"),
  stub("BR-IC-05", "BR-IC"),
  stub("BR-IC-06", "BR-IC"),
  stub("BR-IC-07", "BR-IC"),
  stub("BR-IC-08", "BR-IC"),
  stub("BR-IC-09", "BR-IC"),
  stub("BR-IC-10", "BR-IC"),
  stub("BR-IC-11", "BR-IC"),
  stub("BR-IC-12", "BR-IC"),
  stub("BR-O-01", "BR-O"),
  stub("BR-O-02", "BR-O"),
  stub("BR-O-03", "BR-O"),
  stub("BR-O-04", "BR-O"),
  stub("BR-O-05", "BR-O"),
  stub("BR-O-06", "BR-O"),
  stub("BR-O-07", "BR-O"),
  stub("BR-O-08", "BR-O"),
  stub("BR-O-09", "BR-O"),
  stub("BR-O-10", "BR-O"),
  stub("BR-O-11", "BR-O"),
  stub("BR-O-12", "BR-O"),
  stub("BR-O-13", "BR-O"),
  stub("BR-O-14", "BR-O"),
  stub("BR-S-02", "BR-S"),
  stub("BR-S-03", "BR-S"),
  stub("BR-S-04", "BR-S"),
  stub("BR-S-05", "BR-S"),
  stub("BR-S-06", "BR-S"),
  stub("BR-S-07", "BR-S"),
  stub("BR-S-09", "BR-S"),
  stub("BR-S-10", "BR-S"),
  stub("BR-Z-02", "BR-Z"),
  stub("BR-Z-03", "BR-Z"),
  stub("BR-Z-04", "BR-Z"),
  stub("BR-Z-05", "BR-Z"),
  stub("BR-Z-06", "BR-Z"),
  stub("BR-Z-07", "BR-Z"),
  stub("BR-Z-08", "BR-Z"),
  stub("BR-Z-10", "BR-Z"),
];
